language: node_js
node_js:
- '10'
script:
- npm run build
deploy:
  provider: npm
  email: wenjsen@gmail.com
  api_key:
    secure: DbYEnkqXsrLhDOHd0lfNrWLB2y/VU65VMQugz/Kz+iR1u+tQDaKhAUhQcto+bwW6q8cOOL045jGZWROveo5klHb4iAK8PJkmEH2AzeebsZmiRUhgpfnPeehmQ5VEyOg7jxs5r9ql0DFluc40x1D45OJCtAElaMJQXZfi7soIB0YRreX20gmEV2/FhQT/bU1y3QKqe44NelRKbVKh0IxHHDkR/liRhKXgXIHDDK98UcPOMyxrovLUoslBBbjZeDu9BM6RMSnFG6+CquOJhDqKeI7ANzfFkFJleRsBIyPcmgKVPQoLH2F5ciAnhE3FFbphqgr+XpxAUWI0NbxrpNRT+IGCU5kQmnYe5Nmvxj4wdpaSjaV1biQMNt40267ww5o6ke0nUOdJEDwj7LwVxyKfawjifE16u6o+im6r6dL/QNoZmuOn3SEaXmO9LgsclciVUjOyvg67jLNxvsvN4cg5AfWiYEcayjxJcxrV5OlQ/AIe3XB8YjVo/4Uo7Fqn4XoYSOusgq6+ZQ1bB/7RiVpg7fQORCe5XHtIesf396QyXJZZXCF9ENBzOLbdgJtp3cwL/FZM4jizBub4OSB1Bn1TKeFHZXGoLYxDqpWUmF+hIC74jzI2z9f0/RGsNf08mthDsDyJGPhmBgb5Vl6g2pV7vSMIr/rpCqCqJZI1lYVC5Go=
  skip_cleanup: true
  on:
    tags: true
    repo: wenjiasen/IIOO
